### ISSUE TITLE
感谢楼主

### ISSUE THREAD

**Issue by xuehf** [pzhtpf/WordPress-Editor-iOS-Extension#1]
感谢楼主的分享，如果再写个详细的api文档，相信这个框架会很快被应用并扩展开来。再次感谢

**Comment by pzhtpf** [comment]
嗯呢，后面会努力完善的

------------------ 原始邮件 ------------------
发件人: "xuehf";notifications@github.com;
发送时间: 2016年9月26日(星期一) 中午1:48
收件人: "pzhtpf/WordPress-Editor-iOS-Extension"WordPress-Editor-iOS-Extension@noreply.github.com; 

主题: [pzhtpf/WordPress-Editor-iOS-Extension] 感谢楼主 (#1)

感谢楼主的分享，如果再写个详细的api文档，相信这个框架会很快被应用并扩展开来。再次感谢
